### ISSUE TITLE
Different setups

### ISSUE THREAD

**Issue by sgpjesus** [dssg/aequitas#108]
Projects that use `aequitas` might not require the `cli` package and the `webapp` package. Because of this, making a setup where only the `aequitas` package is installed might be of use. This also has the advantage of removing some heavier dependencies, such as `Flask` and `SQLAlchemy.`

**Comment by mkoistinen** [comment]
Given that there are documented security risks with (very) old versions of Flask and other dependencies, I'd like to vote we move forward with @sgpjesus' proposal and draft PR (though in a slightly modified way)

The way I see it, we have these options:
- Update this package so that Flask no longer needs to be pinned to version *with known "high risk:" vulnerabilities*. (See: [CVE-2018-1000656](https://nvd.nist.gov/vuln/detail/CVE-2018-1000656), [CVE-2019-1010083](https://nvd.nist.gov/vuln/detail/CVE-2019-1010083), [CVE-2023-30861](https://nvd.nist.gov/vuln/detail/CVE-2023-30861))
- Allow be that the webapp and/or cli bits remain included as PIP `extras`. This is very similar to @sgpjesus' draft PR, but is a more standardized way to do this and would work in more use-cases.

**Comment by jesteria** [comment]
Yes: https://github.com/dssg/aequitas/pull/109#issuecomment-1217152335
